### ISSUE TITLE
Macbook screen goes blank??

### ISSUE THREAD

**Issue by mjarkk** [phip1611/mac-sys-info#3]
I'm not sure if this is a problem of this library or just of Mac OS but sometimes when i use this library my macbook screen turns black for about ~0.5 seconds and after that the library returns an error.
In the case of a `.unwrap()`:
```
thread 'actix-rt:worker:0' panicked at 'called `Result::unwrap()` on an `Err` value: CantFetchData', src/utils/system_stat/cpu_info.rs:83:35
```

This is my macbook:
<img width="298" alt="image" src="https://user-images.githubusercontent.com/15320763/104134150-35e83480-5388-11eb-8732-e2d012aef7c1.png">

The above error was caused by some deeply nested code so i have created a loop at the start of my app that just asks this library for information and so far i've only had luck one time when i pressed `CTRL+C` to stop the program:

https://user-images.githubusercontent.com/15320763/104134407-96c43c80-5389-11eb-985e-b997c48dfc8a.MOV

I maybe need to note that my application is started with 
```rust
#[actix_web::main]
async fn main() {
```

Any idea how this could be happening?, when i just spam `sysctl -a` this doesn't happen at all

**Comment by phip1611** [comment]
Hi @mjarkk! I recently had lots of problems with actix-web too because of deeply nested unwrap errors! Can you please check if the following issues solves your problem?
https://github.com/BurntSushi/byteorder/issues/173 / https://github.com/actix/actix-web/issues/1890 

You can quickly fix this with an "cargo update", i.e. transitive "byteorder" dependency must not be 1.4.0 (buggy release).

Maybe you can try to update transitive dependency byteorder first and give me an update 

---

If it fails with "Can't fetch data" then because the function `fork_exec_and_catch` fails: https://github.com/phip1611/mac-sys-info/blob/main/src/lib.rs#L45 

This library used there is here (also by me): https://github.com/phip1611/unix-exec-output-catcher 

PS: Thanks for your interest in my library :)

**Comment by phip1611** [comment]
@mjarkk I published mac-sys-info @ 0.1.13. It should give you a more detailed error message. I hope it helps you to further investigate the issue.

**Comment by mjarkk** [comment]
Thanks, i'll check it again tonight.  

I have also been thinking about this and i think it comes down to the program stopping unexpectedly by the `.unwrap()` that panics or me canceling the program by pressing `CTRL + C`.  
When i handled the error correctly the black screen never happend so it might be because the thread is killed while something is still running in the background that doesn't liked to be killed like that.  
I'll do some more testing tonight and if this is the case it might be worth changing `.unwrap()` to something else in the readme as this kinda scared me at first :)

**Comment by mjarkk** [comment]
So i have updated to the latest version and with that here are my findings.  
1. i cannot get my laptop to blank screen when running just a loop outside of any routes with `get_mac_sys_info().unwrap()` nor does it give any errors.  
2. When running it from a route within actix this black screens every 3 - 5
3. When calling this library about 5 times after each other in a route it blank screens about 2 / 3 of the time.
4. When doing the same as point 3 but 100 times it blank screens almost always but not always some times when i call the route it still doesn't blank screen for some reason
5. When i call `get_mac_sys_info().unwrap()` twice at the same time by spamming the route the library stops working and only gives back an error: `Can't fetch system data because the library reported the error: pipe() failed with error code 24` once this pops up the library doesn't give anything different as response and the blank screens also stop happening.

Tomorrow i'll see if i can create an example app because i currently still testing this is in another project.

**Comment by phip1611** [comment]
The inner library used to retrieve the output of "sysctl -a" uses the UNIX syscalls `fork` and `pipe`. If `pipe()` returns error `24 (Too many open files)` then there are too many open file descriptors. Is there maybe something in your application which opens a lot of file descriptors?! @mjarkk Because your kernel is running out of file descriptors - apparently.

Maybe this helps you: https://superuser.com/questions/433746/is-there-a-fix-for-the-too-many-open-files-in-system-error-on-os-x-10-7-1

**Comment by phip1611** [comment]
@mjarkk  any update?

**Comment by mjarkk** [comment]
Na in the end i started using some other crate called [sysinfo](https://github.com/GuillaumeGomez/sysinfo) that seemed to also contain everything i needed and their code only fetches the required fields using the mac os system APIs and so it's faster for the info i need.

**Comment by mjarkk** [comment]
I'll close the issue, seems like a wired bug inside the system itself i guess.  
If someone else has it i'm happy to re-open it

**Comment by phip1611** [comment]
Alright! Good if sysinfo works for you. Unfortunately it doesn't offer
cache size. That's why I created this crate.
